### ISSUE TITLE
Why a CLA?

### ISSUE THREAD

**Issue by sneak** [signalapp/libsignal-client-node#3]
Per the README:

> Signing a CLA (Contributor License Agreement) is required for all contributions.

Why is a CLA required for contributions to this project if the code is all under the AGPL already?

The Linux kernel, for example, another GPL project, does not require a CLA to contribute.  Requiring one implies the desire to dual-license in the future. What's the deal here?

**Comment by jrose-signal** [comment]
Signal requires a CLA to ensure the contributor agrees to giving Signal explicit permission to use their contributions, as well as represent that the contribution is their own work. Linux moved away from a CLA and to using a DCO (Developer Certificate of Origin) but it serves a similar purpose. 

For the benefit of the project overall, we want to make sure a contributor does not revoke their permission to use their work or infringe on the intellectual property rights of others who might claim they are the true author of a contributed work. At Signal we want to focus our energies on the code rather than legal challenges.
